package main

import (
	"fmt"
	"os"
	
	"strings"
	"text/template"
	"time"
)

const (
	NotesDir   = "Notes"
	ReadmeFile = "README.md"
	HeroGIF    = "https://mir-s3-cdn-cf.behance.net/project_modules/fs/b6374879531965.5cc649b7adaf6.gif"
)

// The Dashboard template now uses HTML-style centering and SVGs
const DashboardTemplate = `<p align="center">
  <img src="` + HeroGIF + `" width="800" alt="Garden Engine">
</p>

<h1 align="center">🌿 DIGITAL GARDEN ENGINE v1.0</h1>

<p align="center">
  <img src="https://img.shields.io/badge/Status-Blooming-brightgreen?style=for-the-badge&logo=github" />
  <img src="https://img.shields.io/badge/Built%20With-Go-00ADD8?style=for-the-badge&logo=go" />
  <img src="https://img.shields.io/badge/Garden-Experimental-blueviolet?style=for-the-badge" />
</p>

---

### 📊 Vital Signs
| Metric | Detail |
| :--- | :--- |
| **Total Seeds** | {{.Count}} Entries |
| **Last Irrigation** | {{.LastUpdated}} |
| **Environment** | GitHub Actions / Go 1.22 |

### 📂 The Growth Archive
| Date | Entry | Status |
| :---: | :--- | :---: |
{{range .Links}}| {{.Date}} | {{.Link}} | 🪴 |
{{end}}

<p align="right"><sub>Generated by the <a href="https://github.com/dill-lk/Digital-Garden">Gardener Bot</a></sub></p>
`

type linkData struct{ Date, Link string }

func main() {
	os.MkdirAll(NotesDir, 0755)

	// 1. Sync the Dashboard
	if err := syncDashboard(); err != nil {
		fmt.Println("❌ Sync Error:", err)
	} else {
		fmt.Println("✨ Aesthetic Dashboard Generated!")
	}
}

func syncDashboard() error {
	files, _ := os.ReadDir(NotesDir)
	var links []linkData
	for _, f := range files {
		if strings.HasSuffix(f.Name(), ".md") {
			date := strings.TrimSuffix(f.Name(), "-seed.md")
			links = append(links, linkData{
				Date: date,
				Link: fmt.Sprintf("**[%s](./Notes/%s)**", f.Name(), f.Name()),
			})
		}
	}

	data := struct {
		Count       int
		LastUpdated string
		Links       []linkData
	}{
		Count:       len(links),
		LastUpdated: time.Now().Format("Jan 02, 2006 | 15:04"),
		Links:       links,
	}

	f, _ := os.Create(ReadmeFile)
	defer f.Close()
	tmpl := template.Must(template.New("dash").Parse(DashboardTemplate))
	return tmpl.Execute(f, data)
}